# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(blank=True, max_length=40)),
                ('dt_vencimento', models.DateField()),
                ('tag', models.CharField(blank=True, max_length=40)),
                ('pago', models.BooleanField(default=False)),
            ],
        ),
    ]
