# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=40)),
                ('cor', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transac.Tag'),
        ),
    ]
