# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transac', '0002_auto_20180315_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='descricao',
            field=models.CharField(max_length=40),
        ),
    ]
