# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-02 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transac', '0003_auto_20180319_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transac.Tag'),
        ),
    ]
