# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
