# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-02 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financ', '0002_auto_20180502_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(max_length=40),
        ),
    ]
