# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financ', '0002_auto_20180403_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='fixo',
            field=models.BooleanField(default=False),
        ),
    ]
