# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-26 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financ', '0003_auto_20180502_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='eliminada',
            field=models.BooleanField(default=False),
        ),
    ]
