# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financ', '0003_despesa_fixo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesa',
            old_name='fixo',
            new_name='fixa',
        ),
    ]
