# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financ', '0004_auto_20180405_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='pk_fixa',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
