# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-09 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financ', '0004_despesa_eliminada'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='parcela',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
