# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-04 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financ', '0005_despesa_parcela'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40)),
                ('dt_import', models.DateField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='despesa',
            name='importacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financ.Importacao'),
        ),
    ]
