# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-29 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financ', '0006_auto_20180904_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'permissions': (('acesso_app_financ', 'Pode acessar Financeiro'),)},
        ),
    ]
