# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-10 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financ', '0008_auto_20191210_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financ.Conta'),
        ),
    ]
