# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-19 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutSkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, max_length=40)),
                ('nome_css', models.TextField(blank=True, max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='layoutskin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.LayoutSkin'),
        ),
    ]
