# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-19 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180919_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='layoutskin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.LayoutSkin'),
        ),
    ]
