# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mensagem_assunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='lida',
            field=models.BooleanField(default=False),
        ),
    ]
