# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180228_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='dt_mensagem',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
