# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('hora', models.TimeField()),
                ('observacao', models.CharField(blank=True, max_length=40)),
                ('tipo', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
