# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 19:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='tipo',
            field=models.CharField(choices=[('Entrada', '1'), ('Saida', '2')], default='1', max_length=9),
        ),
    ]
