# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-18 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_ponto_comprovante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='ponto/comprovantes/'),
        ),
    ]
