# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_auto_20180425_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida')], default='1', max_length=9),
        ),
    ]
