# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0003_auto_20180425_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida')], default='entrada', max_length=9),
        ),
    ]
