# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-27 11:03
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0004_auto_20180426_1156'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ponto',
            managers=[
                ('objects_user', django.db.models.manager.Manager()),
            ],
        ),
    ]
