# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-29 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0004_paramponto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ponto',
            options={'permissions': (('acesso_app_ponto', 'Pode acessar Ponto'),)},
        ),
    ]
