# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-29 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0005_auto_20190529_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ponto',
            options={'permissions': (('acesso_app_ponto', 'Pode acessar Ponto'), ('adicionar_anexo', 'Pode anexar foto'))},
        ),
    ]
